### ISSUE TITLE
Files are missing

### ISSUE THREAD

**Issue by RoelStierum** [FYSETC/Prusa-MK3S-Bear-Upgrade-v2.0#1]
Hi, which files do i need to print? half of them are missing. In this repo there are no extruder files. Could you please add all the files i need?

**Comment by domhardt** [comment]
This repository is mostly useless. I used these official Prusa and Bear repositories and instructions to build my Prusa Bear 2.1 clone:
- [Prusa i3 MK3 repo](https://github.com/prusa3d/Original-Prusa-i3)
- [Prusa i3 MK3 instructions](https://help.prusa3d.com/en/category/original-prusa-i3-mk3-kit-assembly_336)
- [Bear frame repo](https://github.com/gregsaun/prusa_i3_bear_upgrade)
- [Bear frame instructions](https://guides.bear-lab.com/c/Frame)
- [Bear extruder and x axis repo](https://github.com/gregsaun/bear_extruder_and_x_axis)
- [Bear extruder and x axis instructions](https://guides.bear-lab.com/c/Extruder_X_Axis)
